name: helloios

options:
  bundleIdPrefix: com.supergamer474
  xcodeVersion: "15.0"

configs:
  Debug: debug
  Release: release

targets:
  helloios:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources/helloios]
    bundleId: com.supergamer474.helloios
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      SWIFT_VERSION: "5.0"
    info:
      CFBundleDisplayName: "Hello iOS"
      CFBundleName: "helloios"
      CFBundleVersion: "1"
      CFBundleShortVersionString: "1.0"
      UILaunchStoryboardName: "LaunchScreen"
      NSPrincipalClass: "UIApplication"
