name: Hello iOS
options:
  bundleIdPrefix: com.SuperGamer474.helloios
  xcodeVersion: "15.0"
configs:
  Debug: debug
  Release: release
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources/helloios]
    bundleId: com.SuperGamer474.helloios
    info:
      path: Info.plist
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      SWIFT_VERSION: "5.0"
