name: helloios

options:
  bundleIdPrefix: com.SuperGamer474
  xcodeVersion: "15.0"

configs:
  Debug: debug
  Release: release

targets:
  helloios:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: "Info.plist"
    deploymentTarget: "15.0"
    sources: [Sources/helloios]
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "15.0"
      SWIFT_VERSION: "5.0"
