name: Build unsigned iOS .ipa

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-unsigned-ipa:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show Xcode version (debug)
        run: |
          echo "=== xcodebuild -version ==="
          xcodebuild -version || true
          echo "=== sw_vers ==="
          sw_vers || true

      - name: Ensure project.yml and sources exist (debug)
        run: |
          echo "Workspace files:"
          ls -la || true
          echo "project.yml:"
          sed -n '1,200p' project.yml || true

      - name: Build xcodegen from source (install to $HOME/.local/bin)
        run: |
          set -e
          git clone --depth 1 https://github.com/yonaskolb/XcodeGen.git /tmp/XcodeGen
          cd /tmp/XcodeGen
          swift build -c release
          mkdir -p $HOME/.local/bin
          cp .build/release/xcodegen $HOME/.local/bin/xcodegen
          echo "Installed xcodegen to $HOME/.local/bin"

      - name: Generate Xcode project with xcodegen
        run: |
          set -e
          $HOME/.local/bin/xcodegen generate --spec project.yml
          echo "Generated project at: $(pwd)/MyApp.xcodeproj"
          echo "project.pbxproj header (first 60 lines):"
          sed -n '1,60p' MyApp.xcodeproj/project.pbxproj || true

      - name: Try building archive, auto-fix objectVersion on future-format error
        run: |
          set -e
          ARCHIVE_PATH="$PWD/build/MyApp.xcarchive"
          mkdir -p build
          candidates=(77 70 63 60 56 55)
          build_ok=0
          for v in "${candidates[@]}"; do
            echo "----- Attempting build with objectVersion = $v -----"
            /usr/bin/perl -0777 -pe "s/objectVersion = \\d+;/objectVersion = $v;/" -i.bak MyApp.xcodeproj/project.pbxproj || true
            echo "Applied objectVersion $v. Header preview:"
            sed -n '1,20p' MyApp.xcodeproj/project.pbxproj || true
            echo "Running xcodebuild archive..."
            set +e
            xcodebuild clean archive \
              -project MyApp.xcodeproj \
              -scheme MyApp \
              -archivePath "$ARCHIVE_PATH" \
              -sdk iphoneos \
              -configuration Release \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
            rc=$?
            set -e
            if [ $rc -eq 0 ]; then
              echo "xcodebuild succeeded with objectVersion = $v"
              build_ok=1
              break
            else
              echo "xcodebuild failed (exit $rc). Printing last 200 lines from xcodebuild output for debug:"
              tail -n 200 /Users/runner/Library/Logs/DiagnosticReports/* 2>/dev/null || true
              echo "Will try next objectVersion if available."
            fi
          done
          if [ "$build_ok" -ne 1 ]; then
            echo "ERROR: All objectVersion attempts failed. Dumping debug info:"
            echo "===== project.pbxproj header ====="
            sed -n '1,200p' MyApp.xcodeproj/project.pbxproj || true
            echo "===== build directory listing ====="
            ls -la build || true
            exit 74
          fi

      - name: Create unsigned .ipa by packaging .app
        run: |
          set -e
          APP_PATH="$PWD/build/MyApp.xcarchive/Products/Applications/MyApp.app"
          echo "App path: $APP_PATH"
          if [ ! -d "$APP_PATH" ]; then
            echo "ERROR: App not found at expected path. Listing archive contents:"
            ls -la build/MyApp.xcarchive || true
            exit 1
          fi
          mkdir -p build/Payload
          cp -R "$APP_PATH" build/Payload/
          (cd build && zip -r MyApp-unsigned.ipa Payload) || exit 1
          ls -la build/MyApp-unsigned.ipa

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-unsigned-ipa
          path: build/MyApp-unsigned.ipa
