name: Build unsigned iOS .ipa

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-unsigned-ipa:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show Xcode version (debug)
        run: |
          echo "=== xcodebuild -version ==="
          xcodebuild -version || true
          echo "=== sw_vers ==="
          sw_vers || true

      - name: Ensure project.yml and sources exist (debug)
        run: |
          echo "Workspace files:"
          ls -la || true
          echo "project.yml:"
          sed -n '1,200p' project.yml || true

      - name: Build xcodegen from source (install to $HOME/.local/bin)
        run: |
          set -e
          git clone --depth 1 https://github.com/yonaskolb/XcodeGen.git /tmp/XcodeGen
          cd /tmp/XcodeGen
          swift build -c release
          mkdir -p $HOME/.local/bin
          cp .build/release/xcodegen $HOME/.local/bin/xcodegen
          echo "Installed xcodegen to $HOME/.local/bin"

      - name: Generate Xcode project with xcodegen
        run: |
          set -e
          $HOME/.local/bin/xcodegen generate --spec project.yml
          echo "Generated project at: $(pwd)/helloios.xcodeproj"
          echo "project.pbxproj header (first 60 lines):"
          sed -n '1,60p' helloios.xcodeproj/project.pbxproj || true

      - name: Try building archive, auto-fix objectVersion on future-format error
        id: archive-device
        run: |
          set -e
          ARCHIVE_PATH="$PWD/build/helloios.xcarchive"
          mkdir -p build
          candidates=(77 70 63 60 56 55)
          build_ok=0
          for v in "${candidates[@]}"; do
            echo "----- Attempting build with objectVersion = $v -----"
            /usr/bin/perl -0777 -pe "s/objectVersion = \\d+;/objectVersion = $v;/" -i.bak helloios.xcodeproj/project.pbxproj || true
            echo "Applied objectVersion $v. Header preview:"
            sed -n '1,20p' helloios.xcodeproj/project.pbxproj || true
            echo "Running xcodebuild archive..."
            set +e
            xcodebuild clean archive \
              -project helloios.xcodeproj \
              -scheme helloios \
              -archivePath "$ARCHIVE_PATH" \
              -sdk iphoneos \
              -configuration Release \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
            rc=$?
            set -e
            if [ $rc -eq 0 ]; then
              echo "xcodebuild succeeded with objectVersion = $v"
              build_ok=1
              break
            else
              echo "xcodebuild failed (exit $rc). Printing last 200 lines from xcodebuild output for debug (if present):"
              tail -n 200 /Users/runner/Library/Logs/DiagnosticReports/* 2>/dev/null || true
              echo "Will try next objectVersion if available."
            fi
          done
          if [ "$build_ok" -ne 1 ]; then
            echo "ERROR: All objectVersion attempts failed. Dumping debug info:"
            echo "===== project.pbxproj header ====="
            sed -n '1,200p' helloios.xcodeproj/project.pbxproj || true
            echo "===== build directory listing ====="
            ls -la build || true
            exit 74
          fi
          echo "::set-output name=archive_path::$ARCHIVE_PATH"

      - name: Create unsigned .ipa by packaging device .app (iphoneos)
        run: |
          set -e
          ARCHIVE_PATH="$PWD/build/helloios.xcarchive"
          APP_PATH="$ARCHIVE_PATH/Products/Applications/helloios.app"
          OUTPUT_IPA="build/com.SuperGamer474.helloios-unsigned-ios.ipa"
          echo "Device app path: $APP_PATH"
          if [ ! -d "$APP_PATH" ]; then
            echo "ERROR: App not found at expected path. Listing archive contents:"
            ls -la "$ARCHIVE_PATH" || true
            exit 1
          fi
          mkdir -p build/Payload
          rm -rf build/Payload/* || true
          cp -R "$APP_PATH" build/Payload/
          # Create .ipa file (which is just a zip with .ipa extension)
          (cd build && zip -r "$(basename "$OUTPUT_IPA")" Payload) || exit 1
          echo "Created device ipa: $OUTPUT_IPA"
          ls -la "$OUTPUT_IPA" || true

      - name: Build simulator (iphonesimulator) and package simulator .ipa (if possible)
        run: |
          set -e
          echo "Starting simulator build (won't fail the entire job if it fails)."
          SIM_DERIVED="$PWD/build/sim_derived"
          rm -rf "$SIM_DERIVED"
          set +e
          xcodebuild clean build \
            -project helloios.xcodeproj \
            -scheme helloios \
            -configuration Release \
            -sdk iphonesimulator \
            -derivedDataPath "$SIM_DERIVED" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY=""
          rc=$?
          set -e
          if [ $rc -ne 0 ]; then
            echo "Warning: simulator build failed (exit $rc). Will attempt to recover packaging if a simulator .app exists."
          fi

          # Common locations for built simulator .app
          POSSIBLE_APPS=(
            "$SIM_DERIVED/Build/Products/Release-iphonesimulator/helloios.app"
            "$SIM_DERIVED/Build/Products/Debug-iphonesimulator/helloios.app"
            "$PWD/build/Build/Products/Release-iphonesimulator/helloios.app"
            "$PWD/build/Release-iphonesimulator/helloios.app"
          )

          FOUND_APP=""
          for p in "${POSSIBLE_APPS[@]}"; do
            if [ -d "$p" ]; then
              FOUND_APP="$p"
              break
            fi
          done

          if [ -z "$FOUND_APP" ]; then
            echo "Simulator .app not found in expected locations. Listing $SIM_DERIVED contents for debug:"
            ls -la "$SIM_DERIVED" || true
            echo "Skipping simulator .ipa packaging."
            exit 0
          fi

          echo "Found simulator .app at: $FOUND_APP"
          SIM_IPA="build/com.SuperGamer474.helloios-unsigned-iossimulator.ipa"
          mkdir -p build/Payload-sim
          rm -rf build/Payload-sim/* || true
          cp -R "$FOUND_APP" build/Payload-sim/
          (cd build && zip -r "$(basename "$SIM_IPA")" Payload-sim) || exit 1
          echo "Created simulator ipa: $SIM_IPA"
          ls -la "$SIM_IPA" || true

      - name: Upload device unsigned IPA artifact (named as .ipa)
        uses: actions/upload-artifact@v4
        with:
          name: com.SuperGamer474.helloios-unsigned-ios.ipa
          path: build/com.SuperGamer474.helloios-unsigned-ios.ipa

      - name: Upload simulator unsigned IPA artifact (named as .ipa) (ignore if not found)
        uses: actions/upload-artifact@v4
        with:
          name: com.SuperGamer474.helloios-unsigned-iossimulator.ipa
          path: build/com.SuperGamer474.helloios-unsigned-iossimulator.ipa
          if-no-files-found: ignore
